- name: Create a Paloalto Firewall Tunnel
  hosts: 192.168.164.136
  connection: local
  gather_facts: False

  collections:
   - paloaltonetworks.panos 

     
     
  tasks:
  
      

  - name: Configure Tunnel Interface
    panos_tunnel:
        provider: 
          ip_address: 192.168.164.136
          username: admin
          password: admin
        state: 'present'
        if_name: "tunnel.1"
        ip: ['{{ 10.1.1.1/32 }}']
        comment: 'test name'
        zone_name: 'vpn'
        vr_name: 'VR1'
        commit: False
    
  